"""create raw schema and tables

Revision ID: 5ac660f449a8
Revises:
Create Date: 2026-08-21 21:01:35.083367

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ac660f449a8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS raw")
    op.create_table(
        "category_translation",
        sa.Column("product_category_name", sa.Text(), nullable=False),
        sa.Column("product_category_name_english", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("product_category_name"),
        schema="raw",
    )
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.Text(), nullable=False),
        sa.Column("customer_unique_id", sa.Text(), nullable=False),
        sa.Column("customer_zip_code_prefix", sa.Text(), nullable=False),
        sa.Column("customer_city", sa.Text(), nullable=False),
        sa.Column("customer_state", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("customer_id"),
        schema="raw",
    )
    op.create_table(
        "geolocation",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("geolocation_zip_code_prefix", sa.Text(), nullable=False),
        sa.Column("geolocation_lat", sa.Text(), nullable=False),
        sa.Column("geolocation_lng", sa.Text(), nullable=False),
        sa.Column("geolocation_city", sa.Text(), nullable=False),
        sa.Column("geolocation_state", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="raw",
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Text(), nullable=False),
        sa.Column("order_item_id", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Text(), nullable=False),
        sa.Column("seller_id", sa.Text(), nullable=False),
        sa.Column("shipping_limit_date", sa.Text(), nullable=False),
        sa.Column("price", sa.Text(), nullable=False),
        sa.Column("freight_value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("order_id", "order_item_id"),
        schema="raw",
    )
    op.create_table(
        "order_payments",
        sa.Column("order_id", sa.Text(), nullable=False),
        sa.Column("payment_sequential", sa.Text(), nullable=False),
        sa.Column("payment_type", sa.Text(), nullable=False),
        sa.Column("payment_installments", sa.Text(), nullable=False),
        sa.Column("payment_value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("order_id", "payment_sequential"),
        schema="raw",
    )
    op.create_table(
        "order_reviews",
        sa.Column("review_id", sa.Text(), nullable=False),
        sa.Column("order_id", sa.Text(), nullable=False),
        sa.Column("review_score", sa.Text(), nullable=False),
        sa.Column("review_comment_title", sa.Text(), nullable=True),
        sa.Column("review_comment_message", sa.Text(), nullable=True),
        sa.Column("review_creation_date", sa.Text(), nullable=False),
        sa.Column("review_answer_timestamp", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("review_id", "order_id"),
        schema="raw",
    )
    op.create_table(
        "orders",
        sa.Column("order_id", sa.Text(), nullable=False),
        sa.Column("customer_id", sa.Text(), nullable=False),
        sa.Column("order_status", sa.Text(), nullable=False),
        sa.Column("order_purchase_timestamp", sa.Text(), nullable=False),
        sa.Column("order_approved_at", sa.Text(), nullable=True),
        sa.Column("order_delivered_carrier_date", sa.Text(), nullable=True),
        sa.Column("order_delivered_customer_date", sa.Text(), nullable=True),
        sa.Column("order_estimated_delivery_date", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("order_id"),
        schema="raw",
    )
    op.create_table(
        "products",
        sa.Column("product_id", sa.Text(), nullable=False),
        sa.Column("product_category_name", sa.Text(), nullable=True),
        sa.Column("product_name_lenght", sa.Text(), nullable=True),
        sa.Column("product_description_lenght", sa.Text(), nullable=True),
        sa.Column("product_photos_qty", sa.Text(), nullable=True),
        sa.Column("product_weight_g", sa.Text(), nullable=True),
        sa.Column("product_length_cm", sa.Text(), nullable=True),
        sa.Column("product_height_cm", sa.Text(), nullable=True),
        sa.Column("product_width_cm", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("product_id"),
        schema="raw",
    )
    op.create_table(
        "sellers",
        sa.Column("seller_id", sa.Text(), nullable=False),
        sa.Column("seller_zip_code_prefix", sa.Text(), nullable=False),
        sa.Column("seller_city", sa.Text(), nullable=False),
        sa.Column("seller_state", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("seller_id"),
        schema="raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sellers", schema="raw")
    op.drop_table("products", schema="raw")
    op.drop_table("orders", schema="raw")
    op.drop_table("order_reviews", schema="raw")
    op.drop_table("order_payments", schema="raw")
    op.drop_table("order_items", schema="raw")
    op.drop_table("geolocation", schema="raw")
    op.drop_table("customers", schema="raw")
    op.drop_table("category_translation", schema="raw")
    op.execute("DROP SCHEMA IF EXISTS raw")
    # ### end Alembic commands ###
