"""create curated schema and tables

Revision ID: 93a439ad4d44
Revises: 5ac660f449a8
Create Date: 2026-08-25 18:58:11.412890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93a439ad4d44'
down_revision: Union[str, Sequence[str], None] = '5ac660f449a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS curated")
    op.create_table('category_translation',
    sa.Column('category_name', sa.Text(), nullable=False),
    sa.Column('category_name_english', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('category_name'),
    schema='curated'
    )
    op.create_table('persons',
    sa.Column('person_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('person_id'),
    schema='curated'
    )
    op.create_table('zip_code_locations',
    sa.Column('zip_code_prefix', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -34.0 AND 5.3', name='zip_latitude_in_brazil'),
    sa.CheckConstraint('longitude BETWEEN -74.0 AND -34.8', name='zip_longitude_in_brazil'),
    sa.PrimaryKeyConstraint('zip_code_prefix'),
    schema='curated'
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('person_id', sa.Text(), nullable=False),
    sa.Column('zip_code_prefix', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['curated.persons.person_id'], ),
    sa.ForeignKeyConstraint(['zip_code_prefix'], ['curated.zip_code_locations.zip_code_prefix'], ),
    sa.PrimaryKeyConstraint('customer_id'),
    schema='curated'
    )
    op.create_table('products',
    sa.Column('product_id', sa.Text(), nullable=False),
    sa.Column('category_name', sa.Text(), nullable=True),
    sa.Column('name_length', sa.Integer(), nullable=True),
    sa.Column('description_length', sa.Integer(), nullable=True),
    sa.Column('photos_qty', sa.Integer(), nullable=True),
    sa.Column('weight_g', sa.Integer(), nullable=True),
    sa.Column('length_cm', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('width_cm', sa.Integer(), nullable=True),
    sa.CheckConstraint('weight_g IS NULL OR weight_g >= 0', name='products_weight_non_negative'),
    sa.ForeignKeyConstraint(['category_name'], ['curated.category_translation.category_name'], ),
    sa.PrimaryKeyConstraint('product_id'),
    schema='curated'
    )
    op.create_table('sellers',
    sa.Column('seller_id', sa.Text(), nullable=False),
    sa.Column('zip_code_prefix', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['zip_code_prefix'], ['curated.zip_code_locations.zip_code_prefix'], ),
    sa.PrimaryKeyConstraint('seller_id'),
    schema='curated'
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('purchase_timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('delivered_carrier_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('delivered_customer_date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estimated_delivery_date', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('delivered', 'shipped', 'canceled', 'unavailable', 'invoiced', 'processing', 'created', 'approved')", name='orders_status_valid'),
    sa.CheckConstraint('approved_at IS NULL OR approved_at >= purchase_timestamp', name='orders_approved_after_purchase'),
    sa.CheckConstraint('delivered_customer_date IS NULL OR delivered_carrier_date IS NULL OR delivered_customer_date >= delivered_carrier_date', name='orders_delivered_after_despatch'),
    sa.ForeignKeyConstraint(['customer_id'], ['curated.customers.customer_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('customer_id'),
    schema='curated'
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Text(), nullable=False),
    sa.Column('seller_id', sa.Text(), nullable=False),
    sa.Column('shipping_limit_date', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('freight_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('freight_value >= 0', name='order_items_freight_non_negative'),
    sa.CheckConstraint('price >= 0', name='order_items_price_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['curated.orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['curated.products.product_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['curated.sellers.seller_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'order_item_id'),
    schema='curated'
    )
    op.create_table('order_payments',
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('payment_sequential', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Text(), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('installments >= 0', name='order_payments_installments_non_negative'),
    sa.CheckConstraint('value >= 0', name='order_payments_value_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['curated.orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'payment_sequential'),
    schema='curated'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_payments', schema='curated')
    op.drop_table('order_items', schema='curated')
    op.drop_table('orders', schema='curated')
    op.drop_table('sellers', schema='curated')
    op.drop_table('products', schema='curated')
    op.drop_table('customers', schema='curated')
    op.drop_table('zip_code_locations', schema='curated')
    op.drop_table('persons', schema='curated')
    op.drop_table('category_translation', schema='curated')
    op.execute("DROP SCHEMA IF EXISTS curated")
    # ### end Alembic commands ###
